vich_uploader:
    db_driver: orm
    mappings:
        templates:
            uri_prefix: /images/templates
            upload_destination: '%kernel.project_dir%/public/images/templates'
        avatars:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'